spring.application.name=proyectotechstore

#Puerto del servidor
server.port = 8080

#Configuracion PstgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/techstore
spring.datasource.username=postgres
spring.datasource.password=960529
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=TechStoreSecretKey2026SuperSegura
jwt.expiration=86400000