name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        working-directory: ./proyectotechstore
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: ./proyectotechstore
        run: docker build -t techstore-api .

      - name: Tag image
        run: |
          docker tag techstore-api:latest 110760778387.dkr.ecr.us-east-1.amazonaws.com/techstore-api:latest

      - name: Push image
        run: |
          docker push 110760778387.dkr.ecr.us-east-1.amazonaws.com/techstore-api:latest

      - name: Force new deployment
        run: |
          aws ecs update-service \
            --cluster techstore-cluster \
            --service techstore-service \
            --force-new-deployment